"""Blockchain client abstraction.

InMemoryBlockchainClient for tests/CI (no RPC).
Web3BlockchainClient for real chain (minimal, requires web3).
"""

from __future__ import annotations

import re
import time
import hashlib
from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional, Dict


SHA256_RE = re.compile(r"^[0-9a-fA-F]{64}$")


def _validate_hash(evidence_hash: str) -> str:
    if not isinstance(evidence_hash, str):
        raise ValueError(f"evidence_hash must be str, got {type(evidence_hash).__name__}")
    if not SHA256_RE.match(evidence_hash):
        raise ValueError(f"evidence_hash must be 64 hex chars, got: {evidence_hash!r}")
    return evidence_hash.lower()


def hash_to_bytes32(evidence_hash: str) -> bytes:
    """Convert lowercase 64-hex SHA-256 to bytes32 (32 bytes)."""
    h = _validate_hash(evidence_hash)
    return bytes.fromhex(h)


def bytes32_to_hex(b: bytes) -> str:
    if not isinstance(b, (bytes, bytearray)) or len(b) != 32:
        raise ValueError("bytes32 must be 32 bytes")
    return b.hex()


@dataclass
class Anchor:
    evidence_hash: str  # lowercase hex
    submitter: str
    timestamp: int
    manifest_uri: str
    transaction_hash: str
    block_number: int
    contract_address: str


class BlockchainClient(ABC):
    @abstractmethod
    def register(self, evidence_hash: str, manifest_uri: str = "") -> dict:
        """Register evidence_hash, return anchor metadata dict."""
        raise NotImplementedError

    @abstractmethod
    def verify(self, evidence_hash: str) -> Optional[dict]:
        """Return anchor dict if found, else None."""
        raise NotImplementedError

    @abstractmethod
    def get_contract_address(self) -> str:
        raise NotImplementedError


class InMemoryBlockchainClient(BlockchainClient):
    """Deterministic in-memory store for POC/tests."""

    def __init__(self, contract_address: str = "0x0000000000000000000000000000000000000000"):
        self._store: Dict[str, dict] = {}
        self._contract_address = contract_address
        self._block_counter = 0

    def get_contract_address(self) -> str:
        return self._contract_address

    def register(self, evidence_hash: str, manifest_uri: str = "") -> dict:
        h = _validate_hash(evidence_hash)
        if h in self._store:
            raise ValueError(f"duplicate registration for evidence_hash: {h}")
        self._block_counter += 1
        # deterministic tx hash from evidence_hash (not random, for reproducibility)
        tx_hash = "0x" + hashlib.sha256((h + str(self._block_counter)).encode()).hexdigest()[:64]
        anchor = {
            "evidence_hash": h,
            "submitter": "0x0000000000000000000000000000000000000000",
            "timestamp": int(time.time()),
            "manifest_uri": manifest_uri,
            "transaction_hash": tx_hash,
            "block_number": self._block_counter,
            "contract_address": self._contract_address,
        }
        self._store[h] = anchor
        return dict(anchor)

    def verify(self, evidence_hash: str) -> Optional[dict]:
        h = _validate_hash(evidence_hash)
        found = self._store.get(h)
        if found is None:
            return None
        return dict(found)


def load_artifact_abi(artifact_path: str = "contracts/artifacts/EvidenceRegistry.json") -> Optional[list]:
    """Load ABI from compiled artifact if present, else None.

    Artifact is generated by scripts/compile_contract.py and is gitignored locally.
    """
    from pathlib import Path
    import json

    p = Path(artifact_path)
    if not p.exists():
        return None
    try:
        data = json.loads(p.read_text(encoding="utf-8"))
        return data.get("abi")
    except Exception:
        return None


class Web3BlockchainClient(BlockchainClient):
    """Minimal Web3 client for EvidenceRegistry (requires web3 + eth_account)."""

    def __init__(
        self,
        rpc_url: str,
        contract_address: str,
        private_key: str,
        chain_id: int = 1337,
        abi: Optional[list] = None,
    ):
        if not rpc_url:
            raise ValueError("rpc_url is required")
        if not private_key:
            raise ValueError("private_key is required")
        h = _validate_hash("0" * 64)  # validate helper exists
        # lazy import
        try:
            from web3 import Web3
            from eth_account import Account
        except ImportError as e:
            raise ImportError("web3 and eth_account are required for Web3BlockchainClient") from e

        self._Web3 = Web3
        self._Account = Account
        self.rpc_url = rpc_url
        self.chain_id = chain_id
        self.contract_address = contract_address
        self.private_key = private_key
        # Auto-load ABI from artifact if not supplied
        if abi is None:
            abi = load_artifact_abi()
        self.abi = abi

        self.w3 = Web3(Web3.HTTPProvider(rpc_url))
        if not self.w3.is_connected():
            raise ConnectionError(f"cannot connect to RPC: {rpc_url}")
        self.account = Account.from_key(private_key)
        if abi and contract_address:
            self.contract = self.w3.eth.contract(address=self.w3.to_checksum_address(contract_address), abi=abi)
        else:
            self.contract = None

    def get_contract_address(self) -> str:
        return self.contract_address

    def register(self, evidence_hash: str, manifest_uri: str = "") -> dict:
        h = _validate_hash(evidence_hash)
        if self.contract is None:
            raise RuntimeError("contract not initialized (need abi + contract_address)")
        b32 = hash_to_bytes32(h)
        # Never log private_key; do not include in exception messages
        try:
            tx = self.contract.functions.register(b32, manifest_uri).build_transaction(
                {
                    "from": self.account.address,
                    "nonce": self.w3.eth.get_transaction_count(self.account.address),
                    "chainId": self.chain_id,
                    "gas": 200000,
                    "gasPrice": self.w3.eth.gas_price,
                }
            )
            signed = self.account.sign_transaction(tx)
            raw_tx = getattr(signed, "raw_transaction", None) or getattr(signed, "rawTransaction", None)
            tx_hash = self.w3.eth.send_raw_transaction(raw_tx)
            receipt = self.w3.eth.wait_for_transaction_receipt(tx_hash, timeout=120)
            status = getattr(receipt, "status", None)
            # Explicitly handle dict-like receipts
            if status is None and isinstance(receipt, dict):
                status = receipt.get("status")
            if status is not None and int(status) != 1:
                raise RuntimeError(f"blockchain transaction reverted (status={status}) for evidence_hash {h} tx {tx_hash.hex()} block {getattr(receipt, 'blockNumber', receipt.get('blockNumber') if isinstance(receipt, dict) else '?')}")
            return {
                "evidence_hash": h,
                "submitter": self.account.address,
                "timestamp": int(time.time()),
                "manifest_uri": manifest_uri,
                "transaction_hash": tx_hash.hex(),
                "block_number": receipt.blockNumber if hasattr(receipt, "blockNumber") else receipt.get("blockNumber"),  # type: ignore
                "contract_address": self.contract_address,
            }
        except Exception as e:
            # sanitize: never expose private key
            msg = str(e).replace(self.private_key, "***")
            raise RuntimeError(f"Web3 register failed: {msg}") from e

    def verify(self, evidence_hash: str) -> Optional[dict]:
        h = _validate_hash(evidence_hash)
        if self.contract is None:
            raise RuntimeError("contract not initialized")
        b32 = hash_to_bytes32(h)
        try:
            # EvidenceRegistry.verify view returns struct or reverts if not found?
            # Our contract returns boolean + anchor; implement as call
            result = self.contract.functions.verify(b32).call()
            # Expect tuple or struct; adapt to minimal: if exists return dict
            # If contract returns (bool, anchor) handle
            if isinstance(result, (list, tuple)) and len(result) == 2:
                exists, anchor = result
                if not exists:
                    return None
                return {
                    "evidence_hash": h,
                    "submitter": anchor[1] if len(anchor) > 1 else "",
                    "timestamp": int(anchor[2]) if len(anchor) > 2 else 0,
                    "manifest_uri": anchor[3] if len(anchor) > 3 else "",
                    "transaction_hash": "",
                    "block_number": 0,
                    "contract_address": self.contract_address,
                }
            # fallback: if result is struct with timestamp 0 means not found
            if isinstance(result, (list, tuple)):
                # assume anchor struct directly
                if result[2] == 0:
                    return None
                return {
                    "evidence_hash": h,
                    "submitter": result[1],
                    "timestamp": int(result[2]),
                    "manifest_uri": result[3] if len(result) > 3 else "",
                    "transaction_hash": "",
                    "block_number": 0,
                    "contract_address": self.contract_address,
                }
            return None
        except Exception:
            return None
